spring:
  application:
    name: bank_REST
  datasource:
    url: ${BANK_REST_DEV_URL_DB:jdbc:postgresql://localhost:5432/aleksandrkakovkin}
    username: ${BANK_REST_DEV_USERNAME_DB:postgres}
    password: ${BANK_REST_DEV_PASSWORD_DB:postgres}
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog/db.changelog-master.yaml

graphql:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:mysososecretsecretkeyanddontspeak}
  expiration: ${JWT_EXPIRATION_MS:900000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:1800000}

logging:
  level:
    org.springframework.security: INFO

